protected/controllers/PostController.php
<?php
class PostController extends AdminEditableController {
	public $website_id; // For event subscribers. They must know about what website ppl talking about

	public function actionIndex() {
		$box=Yii::app()->innerMail->box($this->owner);
		$pgNr=Yii::app()->request->getQuery('page', 1);
		$folder=$box->getValidFolderID(Yii::app()->request->getQuery('f', UserInnerMailBox::FOLDER_INBOX));
		$folderName=$box->getNameFolderByID($folder);

		$this->title=Yii::t("post", "folder_$folderName"). " - ". CHtml::encode($this->owner->username);

		$headers=$box->getHeaders($pgNr, $pgCnt, $total, $folder);
		$state=$folder==UserInnerMailBox::FOLDER_TRASH ? UserInnerMailBox::FOLDER_STATE_INVISIBLE : UserInnerMailBox::FOLDER_STATE_VISIBLE;

		$senders=array();
		foreach($headers as $header) {
			$senders[]=$header['companion_id'];
		}

		$criteria=new CDbCriteria;
		$criteria->index='id';
		$criteria->addInCondition('id', $senders);

		$summaryText=Helper::getSummaryText($pgNr, $total, Yii::app()->innerMail->headersPageSize);

		$pagination=new CPagination($total);
		$pagination->pageSize=Yii::app()->innerMail->headersPageSize;
		$pagination->currentPage=$pgNr;

		$dropDownItems=$this->renderPartial("dropdown_".$folderName, array(
		), true);

		$this->render("index", array(
			"headers"=>$headers,
			"folder"=>$folder,
			"total"=>$total,
			"pgCnt"=>$pgCnt,
			"pgNr"=>$pgNr,
			"box"=>$box,
			"dropDownItems"=>$dropDownItems,
			"pagination"=>$pagination,
			"senders"=>User::model()->findAll($criteria),
			"summaryText"=>$summaryText,
			"state"=>$state,
		));
	}

	public function actionChain($id) { // header_id
		$innerMail=Yii::app()->innerMail;
		$box = $innerMail->box($this->owner);
		if(!$header = $box->getHeader($id)) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}

		$companion=User::model()->findByPk($header['companion_id']);

		$form=new PostForm;
		if(isset($_POST['PostForm']) AND is_array($_POST['PostForm'])) {
			$form->attributes=$_POST['PostForm'];
			$form->companion_id=$header['companion_id'];
			if($form->validate()) {
				$innerMail->attachEventHandler('onAddToChain', array('PostEvent', 'sendEmailOnMessageSent'));
				if($box->addToChain($header, $companion, $form->message)) {
					Yii::app()->user->setFlash('success', Yii::t("post", "Message has been sent"));
				} else {
					Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
				}
				$this->refresh();
			}
		}

		$pgNr=Yii::app()->request->getQuery('page', 1);
		$messages = $box->getMessages($header['id'], $pgNr, $pgCnt, $total);

		$messageTmpl=$this->renderPartial("messages", array(
			"pgNr"=>$pgNr,
			"pgCnt"=>$pgCnt,
			"messages"=>$messages,
			"box"=>$box,
			"companion"=>$companion,
			"user"=>$this->owner,
			"header"=>$header,
		), true);

		if(Yii::app()->request->isAjaxRequest) {
			exit($messageTmpl);
		}

		if(!$this->invisible) {
			$box->markAsRead($header['id']);
		}

		$block=$box->getBlock($header['companion_id']);
		$bind=BindWebsite::model()->with(array(
			"sale"=>array(
				"with"=>array(
					"website"=>array("select"=>"price, domain, idn"),
				),
			),
		))->findByPk($header['chain_id']);

		Yii::app()->clientScript->registerScriptFile(Yii::app()->request->getBaseUrl(true).'/js/jquery.scroll.js');
		Yii::app()->clientScript->registerCssFile(Yii::app()->request->getBaseUrl(true).'/css/chat.css');

		if($bind) {
			$sale=$bind->sale;
			$website=$bind->sale->website;
		} else {
			$sale=$website=null;
		}

		$this->title=Yii::t("post", "Chat with {Username}", array(
			"{Username}"=>CHtml::encode($companion->username),
		));

		$widget=$this->renderPartial("chat_widget", array(
			"form"=>$form,
			"companion"=>$companion,
			"user"=>$this->owner,
			"header"=>$header,
			"box"=>$box,
			"messages"=>$messageTmpl,
			"block"=>$block,
			"sale"=>$sale,
			"website"=>$website,
		), true);

		$this->render("add", array(
			"widget"=>$widget,
			"sale"=>$sale,
			"website"=>$website,
			"user"=>$this->owner,
		));
	}

	public function actionSend($id) { // website_id
		$onSale=Sale::model()->with(array(
			"website"=>array("select"=>"domain, price, idn"),
			"category"=>array("with"=>"translations"),
			//"user"=>array("scopes"=>array("active","confirmed"))
			"user",
		))->findByPk($id);
		if(!$onSale) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		$this->website_id=$onSale->website->id;

		$scenario='new';
		$form=new PostForm($scenario);
		$box = Yii::app()->innerMail->box($this->owner);

		if(isset($_POST['PostForm']) AND is_array($_POST['PostForm'])) {
			$form->attributes=$_POST['PostForm'];
			$form->companion_id=$onSale->user->id;
			if($form->validate()) {
				$innerMail=Yii::app()->innerMail;
				$innerMail->attachEventHandler('onNewMessageCreated', array('PostEvent', 'sendEmailOnMessageSent'));
				$innerMail->attachEventHandler('onNewMessageCreated', array('PostEvent', 'bindWebsite'));
				if($box -> createNewMessage($onSale->user, $form->subject, $form->message)) {
					Yii::app()->user->setFlash('success', Yii::t("post", "Message has been sent"));
					$this->redirect(array("post/index"));
				} else {
					Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
					$this->refresh();
				}
			}
		}
		$this->title=Yii::t("post", "New message");
		$block=$box->getBlock($onSale->user->id);

		$widget = $this->renderPartial("new", array(
			"sale"=>$onSale,
			"website"=>$onSale->website,
			"user"=>$this->owner,
			"form"=>$form,
			"block"=>$block,
		), true);

		$this->render("add", array(
			"widget"=>$widget,
			"sale"=>$onSale,
			"website"=>$onSale->website,
		));
	}

	public function actionBlockedUsers() {
		$pgNr=Yii::app()->request->getQuery('page', 1);
		$box=Yii::app()->innerMail->box($this->owner);
		$blocked = $box->getBlockedUsers($pgNr, $pgCnt, $total);
		$criteria=new CDbCriteria;
		$criteria->select="username, id, status";
		$criteria->index="id";
		$criteria->addInCondition('id', array_keys($blocked));
		$users=User::model()->findAll($criteria);
		$summaryText=Helper::getSummaryText($pgNr, $total, Yii::app()->innerMail->blockedUsersPageSize);
		$this->title=Yii::t("post", "Blocked users");

		$this->render("blocked_users", array(
			"users"=>$users,
			"blocked"=>$blocked,
			"pgNr"=>$pgNr,
			"pgCnt"=>$pgCnt,
			"summaryText"=>$summaryText,
		));
	}

	public function actionBlockSender($id) { // User id (User which will be blocked by current user)
		if(!$blockedUser=User::model()->findByPk($id)) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		$box = Yii::app()->innerMail->box($this->owner);
		if($box->blockSender($blockedUser)) {
			Yii::app()->user->setFlash('success', Yii::t("post", "User has been blocked"));
		} else {
			Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
		}
		$this->redirectBack();
	}

	public function actionUnblockSender($id) { // Blocked user id
		if(!$blockedUser=User::model()->findByPk($id)) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		$box = Yii::app()->innerMail->box($this->owner);
		if($box->unBlockSender($blockedUser)) {
			Yii::app()->user->setFlash('success', Yii::t("post", "User has been unblocked"));
		} else {
			Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
		}
		$this->redirectBack();
	}

	public function actionReportScam($id) {
		$blockedUser=User::model()->findByPk($id);
		if(!$blockedUser=User::model()->findByPk($id)) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		$box = Yii::app()->innerMail->box($this->owner);
		$chain_id=Yii::app()->request->getQuery('chain_id');
		if(!$header=$box->getHeaderByChainID($chain_id)) {
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		if($box->reportScam($blockedUser, $chain_id)) {
			Yii::app()->user->setFlash('success', Yii::t("post", "User has been blocked and marked as a spammer"));
		} else {
			Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
		}
		$this->redirectBack();
	}

	public function actionRestoreFromTrash() {
		$box = Yii::app()->innerMail->box($this->owner);
		if(isset($_POST['header']) AND is_array($_POST['header'])) {
			if($box->restoreFromTrash($_POST['header'])) {
				Yii::app()->user->setFlash('success', Yii::t("post", "Messages have been restored"));
			} else {
				Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
			}
		}
		$this->redirectBack();
	}

	public function actionCompletelyRemove() {
		$box = Yii::app()->innerMail->box($this->owner);
		if(isset($_POST['header']) AND is_array($_POST['header'])) {
			if($box->completelyRemove($_POST['header'])) {
				Yii::app()->user->setFlash('success', Yii::t("post", "Messages have been completely removed"));
			} else {
				Yii::app()->user->setFlash('danger', Yii::t("notification", "An internal error occurred. Please try again later"));
			}
		}
		$this->redirectBack();
	}

	public function actionMoveToTrash() {
		$box = Yii::app()->innerMail->box($this->owner);
		if(isset($_POST['header']) AND is_array($_POST['header'])) {
			$rows=$box->moveToTrashFolder($_POST['header']);
			Yii::app()->user->setFlash('success', Yii::t("post", "Selected messages have been moved to trash folder"));
		}
		$this->redirectBack();
	}

	public function actionMarkAsRead() {
		$box = Yii::app()->innerMail->box($this->owner);
		if(isset($_POST['header']) AND is_array($_POST['header'])) {

protected/views/front/post/blocked_users.php
<h1><?php echo CHtml::encode($this->title) ?></h1>
<hr>
<div class="btn-group btn-group-md">
	<a href="<?php echo $this->createUrl("post/index") ?>" class="btn btn-info"><i class="fa fa-inbox"></i>&nbsp;&nbsp;<?php echo Yii::t("post", "Back to Inbox") ?></a>
</div>

<table class="table table-hover">
	<thead>
		<tr>
			<th><?php echo Yii::t("user", "Username") ?></th>
			<th><?php echo Yii::t("post", "Blocked at") ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($blocked as $id=>$block): ?>
		<tr>
			<td>
				<?php echo CHtml::encode($users[$id]->username) ?>
			</td>

			<td>
				<?php echo Yii::app()->dateFormatter->formatDateTime($block['block_date'], 'long', 'medium'); ?>
			</td>

			<td>
				<a class="btn btn-sm btn-primary" href="<?php echo $this->createUrl("post/unblock-sender", array("id"=>$id)) ?>"><?php echo Yii::t("post", "Unblock") ?></a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	<thead>
		<tr>
				<th colspan="3" class="text-center">
						<a href="<?php echo $this->createUrl("post/blocked-users", array("page"=>$pgNr-1)) ?>" class="btn btn-sm btn-primary<?php echo ($pgNr<=1) ? " disabled" : null?>">
								<i class="fa fa-angle-left"></i>
						</a>
						<a href="<?php echo $this->createUrl("post/blocked-users", array("page"=>$pgNr+1)) ?>" class="btn btn-sm btn-primary<?php echo ($pgNr>=$pgCnt) ? " disabled" : null?>">
								<i class="fa fa-angle-right"></i>
						</a>
						<span class="pull-right"><?php echo $summaryText ?></span>
				</th>
		</tr>
	</thead>
</table>

protected/views/front/post/chat_widget.php
<script type="text/javascript">
$(document).ready(function() {
	$('#chat').jscroll({
		debug: true,
		loadingHtml: '<small><?php echo Yii::t("post", "Loading...") ?></small>&nbsp;<i class="fa fa-spinner fa-spin"></i>'
	});
});
</script>

<div class="btn-group btn-group-sm">
	<a href="<?php echo $this->createUrl("post/index") ?>" class="btn btn-info"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;<?php echo Yii::t("post", "Back to Inbox") ?></a>
	<?php if($website): ?>
	<a href="<?php echo $this->createUrl("website/show", array("domain"=>$website->domain)) ?>" class="btn btn-success btn-sm" target="_blank"><i class="fa fa-usd"></i> &nbsp;&nbsp;<?php echo Yii::t("website", "Estimate Price") ?></a>
	<a href="http://<?php echo $website->domain ?>" class="btn btn-default" target="_blank"><i class="fa fa-globe"></i> &nbsp;&nbsp;<?php echo Yii::t("sale", "Visit website") ?></a>
	<?php endif; ?>

	<div class="btn-group btn-group-sm">
		<button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
			<i class="fa fa-angle-double-down"></i> &nbsp;&nbsp; <?php echo Yii::t("post", "Action") ?>
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			<li>
				<a href="<?php echo $this->createUrl("post/block-sender", array("id"=>$header['companion_id'])) ?>">
					<i class="fa fa-ban"></i> &nbsp;&nbsp; <?php echo Yii::t("post", "Block Sender") ?>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->createUrl("post/report-scam", array("id"=>$header['companion_id'], "chain_id"=>$header['chain_id'])) ?>">
					<i class="fa fa-warning"></i> &nbsp;&nbsp; <?php echo Yii::t("post", "Scammer!") ?>
				</a>
			</li>
		</ul>
	</div>
</div>
<div class="panel panel-primary">
		<div class="panel-heading">
				<span class="glyphicon glyphicon-comment"></span> <?php echo Yii::t("post", "Chat") ?>
		</div>
		<div class="panel-body">
			<ul class="chat" id="chat">
				<?php echo $messages ?>
			</ul>
		</div>
		<div class="panel-footer">
			<div class="input-group" style="width: 100%">
				<?php if($block['external']): ?>
					<p><?php echo Yii::t("post", "This user has blocked you") ?></p>
				<?php elseif($block['internal']): ?>
					<p>
						<?php echo Yii::t("post", "You have blocked this user. {Click here} to unblock", array(
							"{Click here}"=>CHtml::link(Yii::t("misc", "Click here") , array("unblock-sender", "id"=>$companion->id)),
						)) ?>
					</p>
				<?php elseif(!$user->canSendMessage()): ?>
					<p><?php echo Yii::t("post", "You are forbidden to send messages") ?></p>
				<?php else: ?>
					<form method="POST" style="width:100%">

					<?php echo CHtml::errorSummary($form, null, null, array(
						'class' => 'alert alert-danger',
					)); ?>

					<?php echo CHtml::activeTextArea($form, 'message', array(
						'class' => 'form-control',
						'placeholder'=>Yii::t("post", "Type your message here..."),
					)); ?>
					<br/><br/><br/>
					<span class="input-group-btn">
						<button class="btn btn-warning btn-sm" id="btn-chat" type="submit">
							<?php echo Yii::t("post", "Send message"); ?>
						</button>
					</span>
					</form>
				<?php endif; ?>
			</div>
		</div>
</div>

protected/views/front/post/dropdown_important.php
<li>
<a href="<?php echo $this->createUrl("post/mark-as-read") ?>" class="inbox-operation">
	<i class="fa fa-pencil"></i>&nbsp;<?php echo Yii::t("post", "Mark as Read") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/mark-as-star") ?>" class="inbox-operation">
	<i class="fa fa-star"></i>&nbsp;<?php echo Yii::t("post", "Mark as Starred") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/remove-from-important") ?>" class="inbox-operation">
	<i class="fa fa-bookmark-o"></i>&nbsp;<?php echo Yii::t("post", "Remove from Important folder") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/move-to-trash") ?>" class="inbox-operation">
	<i class="fa fa-trash-o"></i>&nbsp;<?php echo Yii::t("post", "Move to Trash") ?>
</a>
</li>

protected/views/front/post/dropdown_inbox.php
<li>
<a href="<?php echo $this->createUrl("post/mark-as-read") ?>" class="inbox-operation">
	<i class="fa fa-pencil"></i>&nbsp;<?php echo Yii::t("post", "Mark as Read") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/mark-as-star") ?>" class="inbox-operation">
	<i class="fa fa-star"></i>&nbsp;<?php echo Yii::t("post", "Mark as Starred") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/mark-as-important") ?>" class="inbox-operation">
	<i class="fa fa-bookmark"></i>&nbsp;<?php echo Yii::t("post", "Mark as Important") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/move-to-trash") ?>" class="inbox-operation">
	<i class="fa fa-trash-o"></i>&nbsp;<?php echo Yii::t("post", "Move to Trash") ?>
</a>
</li>

protected/views/front/post/dropdown_sent.php
<li>
<a href="<?php echo $this->createUrl("post/mark-as-star") ?>" class="inbox-operation">
	<i class="fa fa-star"></i>&nbsp;<?php echo Yii::t("post", "Mark as Starred") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/mark-as-important") ?>" class="inbox-operation">
	<i class="fa fa-bookmark"></i>&nbsp;<?php echo Yii::t("post", "Mark as Important") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/move-to-trash") ?>" class="inbox-operation">
	<i class="fa fa-trash-o"></i>&nbsp;<?php echo Yii::t("post", "Move to Trash") ?>
</a>
</li>

protected/views/front/post/dropdown_starred.php
<li>
<a href="<?php echo $this->createUrl("post/mark-as-read") ?>" class="inbox-operation">
	<i class="fa fa-pencil"></i>&nbsp;<?php echo Yii::t("post", "Mark as Read") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/remove-from-star") ?>" class="inbox-operation">
	<i class="fa fa-star-o"></i>&nbsp;<?php echo Yii::t("post", "Remove from Starred folder") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/mark-as-important") ?>" class="inbox-operation">
	<i class="fa fa-bookmark"></i>&nbsp;<?php echo Yii::t("post", "Mark as Important") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/move-to-trash") ?>" class="inbox-operation">
	<i class="fa fa-trash-o"></i>&nbsp;<?php echo Yii::t("post", "Move to Trash") ?>
</a>
</li>

protected/views/front/post/dropdown_trash.php
<li>
<a href="<?php echo $this->createUrl("post/restore-from-trash") ?>" class="inbox-operation">
	<i class="fa fa-mail-reply-all"></i>&nbsp;<?php echo Yii::t("post", "Restore from Trash folder") ?>
</a>
</li>
<li>
<a href="<?php echo $this->createUrl("post/completely-remove") ?>" class="inbox-operation">
	<i class="fa fa-trash-o"></i>&nbsp;<?php echo Yii::t("post", "Completely remove") ?>
</a>
</li>

protected/views/front/post/index.php
<script type="text/javascript">
    $(document).ready(function(){
        $("#checkAll").on("click", function(){
            if ($(this).is(':checked')) {
                $(".headers").prop("checked", true);
            } else {
                $(".headers").prop("checked", false);
            }
        });
        $(".inbox-operation").on("click", function() {
					var $href=$(this).attr("href");
					var form=document.getElementById("header_form");
					form.action=$href;
					form.submit();
					return false;
        });
    })
</script>
<h1><i class="fa fa-inbox"></i>&nbsp;<?php echo Yii::t("post", "My messages") ?></h1>
<hr>

<div class="row email">
    <div id="list-toggle" class="col-md-2">
        <ul class="emailNav nav nav-pills nav-stacked margin-bottom-10">
            <li class="inbox<?php echo $folder==UserInnerMailBox::FOLDER_INBOX ? " active" : null ?>">
                <a href="<?php echo $this->createUrl("post/index", array("f"=>UserInnerMailBox::FOLDER_INBOX)) ?>">
                <i class="fa fa-inbox fa-fw"></i> <?php echo Yii::t("post", "folder_inbox") ?>
                <?php echo $this->newMessages > 0 ? "(". $this->newMessages .")" : null; ?>
                </a>
            </li>
            <li class="sent<?php echo $folder==UserInnerMailBox::FOLDER_SENT ? ' active' : null ?>">
                <a href="<?php echo $this->createUrl("post/index", array("f"=>UserInnerMailBox::FOLDER_SENT)) ?>">
                <i class="fa fa-mail-forward fa-fw"></i> <?php echo Yii::t("post", "folder_sent") ?>
                </a>
            </li>
            <li class="starred<?php echo $folder==UserInnerMailBox::FOLDER_STARRED ? ' active' : null ?>">
            <a href="<?php echo $this->createUrl("post/index", array("f"=>UserInnerMailBox::FOLDER_STARRED)) ?>">
                <i class="fa fa-star fa-fw"></i> <?php echo Yii::t("post", "folder_starred") ?>
            </a>
            </li>
            <li class="important<?php echo $folder==UserInnerMailBox::FOLDER_IMPORTANT ? ' active' : null ?>">
            <a href="<?php echo $this->createUrl("post/index", array("f"=>UserInnerMailBox::FOLDER_IMPORTANT)) ?>">
                <i class="fa fa-bookmark fa-fw"></i> <?php echo Yii::t("post", "folder_important") ?>
            </a>
            </li>
            <li class="trash<?php echo $folder==UserInnerMailBox::FOLDER_TRASH ? ' active' : null ?>">
                <a href="<?php echo $this->createUrl("post/index", array("f"=>UserInnerMailBox::FOLDER_TRASH)) ?>">
                    <i class="fa fa-trash-o fa-fw"></i> <?php echo Yii::t("post", "folder_trash") ?>
                </a>
            </li>
            <li class="spam">
            <a href="<?php echo $this->createUrl("post/blocked-users") ?>">
                <span class="fa-stack">
                  <i class="fa fa-user fa-stack-1x"></i>
                  <i class="fa fa-ban fa-stack-2x text-danger"></i>
                </span><?php echo Yii::t("post", "Blocked users") ?>
            </a>
            </li>
        </ul>
    </div>
    <div class="col-md-10">
          <table class="table table-hover">
             <thead>
                <tr>
                    <th>
                        <span><input type="checkbox" id="checkAll">
                    </th>
                   <th colspan="3">
                         <div class="btn-group">
                             <button class="btn btn-light-grey dropdown-toggle" data-toggle="dropdown"> <?php echo Yii::t("post", "Action") ?>
                                <i class="fa fa-caret-down"></i>
                             </button>
                             <ul class="dropdown-menu context" role="menu">
															<?php echo $dropDownItems ?>
                             </ul>
                         </div>
                   </th>
                    <th colspan="3">
                        <a href="<?php echo $this->createUrl("post/index") ?>" class="btn btn-default pull-right">
                            <i class="fa fa-refresh"></i>&nbsp;<?php echo Yii::t("post", "Refresh") ?>
                        </a>
                    </th>
                </tr>
             </thead>
             <tbody>
							<form method="POST" id="header_form">
                <?php foreach($headers as $header): ?>
                    <?php
                        $new=$box->isNew($header['status']);
                        $username=CHtml::encode(Helper::mb_ucfirst($senders[$header['companion_id']]->username));
                        $subject=CHtml::encode(Helper::mb_ucfirst($header['subject']));
                        $url=$this->createUrl("post/chain", array("id"=>$header['id']));
                    ?>
                    <tr<?php echo $box->isNew($header['status']) ? ' class="active"' : null ?>>
                        <td width="15px">
                            <input type="checkbox" class="headers" name="header[]" value="<?php echo $header['id'] ?>">
                        </td>
                        <td width="15px"><i class="fa fa-star<?php echo !$box->isInStarredFolder($header['id'], $state) ? "-o" : null ?>"></i></td>
                        <td width="15px"><i class="fa fa-bookmark<?php echo !$box->isInImportantFolder($header['id'], $state) ? "-o" : null ?>"></i></td>
                        <td>
													<a class="mail-link" href="<?php echo $url; ?>">
													<?php if($new): ?>
															<strong><?php echo $username ?></strong>
													<?php else: ?>
															<?php echo $username ?>
													<?php endif; ?>
													</a>
                        </td>
                        <td>
													<a class="mail-link" href="<?php echo $url; ?>">
                            <?php if($new): ?>
                                <span class="label label-success"><?php echo Yii::t("post", "New") ?></span>
                                <strong><?php echo $subject ?></strong>
                            <?php else: ?>
                                <?php echo $subject ?>
                            <?php endif; ?>
													</a>
                        </td>
                        <td class="text-right">
													<a class="mail-link" href="<?php echo $url; ?>">
														<?php echo Helper::time_elapsed_string($header['appeared_date']) ?>
													</a>
												</td>
                    </tr>
                <?php endforeach; ?>
							</form>
             </tbody>

             <thead>
                <tr>
                   <th colspan="6" class="text-center">
                        <a href="<?php echo $this->createUrl("post/index", array("f"=>$folder, "page"=>$pgNr-1)) ?>" class="btn btn-sm btn-primary<?php echo ($pgNr<=1) ? " disabled" : null?>">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a href="<?php echo $this->createUrl("post/index", array("f"=>$folder, "page"=>$pgNr+1)) ?>" class="btn btn-sm btn-primary<?php echo ($pgNr>=$pgCnt) ? " disabled" : null?>">
                            <i class="fa fa-angle-right"></i>
                        </a>
                       <span class="pull-right"><?php echo $summaryText ?></span>
                   </th>
                </tr>
             </thead>
          </table>
    </div>
</div>