protected/models/User.php
<?php
class User extends CActiveRecord {
	const STATUS_ACTIVE = 1;
	const STATUS_BLOCKED = 0;
	const STATUS_DELETED = 2;

	const ROLE_USER = 'user';
	const ROLE_ADMIN = 'administrator';
	const ROLE_ROOT = 'root';

	const EMAIL_CONFIRMED = 1;
	const EMAIL_NOTCONFIRMED = 0;

	const ALLOW_MESSAGE = 1;
	const DISALLOW_MESSAGE = 0;

	/**
	* @param string $className
	* @return User instance
	*/
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function relations() {
		return array(
			'tokens'=>array(self::HAS_MANY, 'UserToken', 'user_id'),
			'onsale'=>array(self::HAS_MANY, 'Sale', 'user_id'),
		);
	}

	public function tableName() {
		return '{{user}}';
	}

	public function isActive() {
		return !in_array($this->status, array(self::STATUS_BLOCKED, self::STATUS_DELETED));
	}

	public static function getStatusList() {
		return array(
			self::STATUS_ACTIVE => Yii::t("user", 'Active'),
			self::STATUS_BLOCKED => Yii::t("user", 'Blocked'),
			self::STATUS_DELETED => Yii::t("user", 'Deleted'),
		);
	}

	public function getStatusCSS() {
		switch($this->status) {
			case self::STATUS_BLOCKED:
				return 'warning';
			break;
			case self::STATUS_DELETED:
				return 'danger';
			break;
			default:
				return null;
			break;
		}
	}

	public static function getRoleList() {
		return array(
			self::ROLE_USER => Yii::t("user", 'User'),
			self::ROLE_ADMIN => Yii::t("user", 'Administrator'),
            self::ROLE_ROOT => Yii::t("user", 'Root'),
		);
	}

	public function getRoleMessage() {
		switch($this->role) {
			case self::ROLE_USER:
				return Yii::t("user", 'User');
			break;
			case self::ROLE_ADMIN:
				return Yii::t("user", 'Administrator');
			break;
			case self::ROLE_ROOT:
				return Yii::t("user", 'Root');
			break;
			default:
				return Yii::t("user", 'Unknown');
			break;
		}
	}

	public function getStatusMessage() {
		switch($this->status) {
			case self::STATUS_ACTIVE:
				return Yii::t("user", 'Active');
			break;
			case self::STATUS_BLOCKED:
				return Yii::t("user", 'Blocked');
			break;
			case self::STATUS_DELETED:
				return Yii::t("user", 'Deleted');
			break;
			default:
				return null;
			break;
		}
	}

	public function beforeSave() {
		if(parent::beforeSave()) {
			$now = date("Y-m-d H:i:s");
			if($this->isNewRecord) {
				$this->registered_at = $now;
				$this->modified_at = $now;
				$this->last_login_at = $now;
				$this->ip = $this->last_ip_login = Yii::app()->getRequest()->getUserHostAddress();
			} else {
				$this->modified_at = $now;
			}
			return true;
		} else {
			return false;
		}
	}

	public function beforeDelete() {
		return false;
	}

	public function hasConfirmedEmail() {
		return $this->email_confirmed == self::EMAIL_CONFIRMED;
	}

	public function canSendMessage() {
		return $this->can_send_message == self::ALLOW_MESSAGE;
	}

	public function isSuperUser() {
		return $this->role == self::ROLE_ROOT;
	}

	public function scopes() {
		return array(
			'adminIndex' => array(
				'condition'=>'role NOT IN(:root)',
				'params' => array(':root' => self::ROLE_ROOT),
				'order'=>'registered_at DESC',
			),
			'active'=>array(
				'condition'=>'status=:status',
				'params'=>array(':status'=>self::STATUS_ACTIVE),
			),
			'confirmed'=>array(
				'condition'=>'email_confirmed=:email_confirmed',
				'params'=>array(':email_confirmed'=>self::EMAIL_CONFIRMED),
			),
		);
	}

	public $password2;
	public function rules() {
		return array(
			array('email, username', 'required'),
			array('email_confirmed, role, can_send_message, status, lang_id', 'required', 'on'=>array('adminCreate', 'adminUpdate')),

			// Password required only on create
			array('password, password2', 'required', 'except'=>array('adminUpdate')),
			array('password, password2', 'length', 'min' => 5, 'except'=>array('adminUpdate')),
			array('password2', 'compare', 'compareAttribute' => 'password', 'except'=>array('adminUpdate'), 'message' => Yii::t("user", "Passwords do not match")),

			array('email', 'length', 'max' => 80),
			array('username', 'length', 'max' => 30),
			array('email', 'email'),
			array('email, username', 'unique'),

			// Admin create
			array('email_confirmed', 'in', 'range' => array(self::EMAIL_NOTCONFIRMED, User::EMAIL_CONFIRMED), 'on'=>array('adminCreate', 'adminUpdate')),
			array('role', 'in', 'range' => array_keys(self::getRoleList()), 'on'=>array('adminCreate', 'adminUpdate')),
			array('can_send_message', 'in', 'range' => array(self::DISALLOW_MESSAGE, User::ALLOW_MESSAGE), 'on'=>array('adminCreate', 'adminUpdate')),
			array('status', 'in', 'range' => array_keys(self::getStatusList()), 'on'=>array('adminCreate', 'adminUpdate')),
            array('lang_id', 'existsLanguage', 'on'=>array('adminCreate', 'adminUpdate')),
			// Search
			array('id, email, username, registered_at, status, ip, role, email_confirmed', 'safe', 'on' => 'search'),
		);
	}

    public function existsLanguage() {
        if($this -> hasErrors()) {
            return false;
        }
        if(!Language::model()->issetLang($this->lang_id)) {
            $this->addError("language", Yii::t("language", "The language {Language} doesn't exists in the system", array(
                "{Language}" => "<strong>".$this->language."</strong>",
            )));
        }
    }

	public function attributeLabels() {
		return array(
			"id"=>Yii::t("misc", "ID"),
			"email"=>Yii::t("user", "Email"),
			"username"=>Yii::t("user", "Username"),
			"email_confirmed"=>Yii::t("user", "Email confirmation"),
			"role"=>Yii::t("user", "User role"),
			"can_send_message"=>Yii::t("user", "Can send message"),
			"status"=>Yii::t("user", "User status"),
			"password"=>Yii::t("user", "Password"),
			"password2"=>Yii::t("user", "Re-Password"),
			"registered_at"=>Yii::t("user", "Registered at"),
			"modified_at"=>Yii::t("user", "Modified at"),
			"last_login_at"=>Yii::t("user", "Last login at"),
			"ip"=>Yii::t("website", "IP Address"),
			"last_ip_login"=>Yii::t("user", "Last login IP Address"),
			"lang_id"=>Yii::t("misc", "Language"),
		);
	}

	public function search() {
		$criteria=new CDbCriteria;
		$criteria -> order = 'registered_at DESC';
		$criteria -> compare('id', $this -> id);
		$criteria -> compare('username', $this -> username, true);
		$criteria -> compare('email', $this -> email, true);
		$criteria -> compare('role', $this -> role);
		$criteria -> compare('status', $this -> status);
		return new CActiveDataProvider($this->adminIndex(), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/UserController.php
<?php
class UserController extends FrontController {
	public function events() {
		return array(
			'onUserCreated' => array(
				array('UserEvent', 'sendTokenOnEmail'),
				array('UserEvent', 'createUserServer'),
			),
		);
	}

	public function actionSignIn() {
		$user = Yii::app() -> user;
		if(!$user->isGuest) {
			Yii::app()->user->logout();
		}
		$this->title=Yii::t("user", "Sign in") ." | ". Helper::getInstalledUrl();

		$cnt = Yii::app() -> params["badLoginCount"];
		$scenario = ($cnt >= 0 AND $user -> getState('badLoginCount', 0) >= $cnt) ? 'loginLimit' : null;
		$loginForm = new LoginForm($scenario);

		if(Yii::app() -> request -> isPostRequest AND !empty($_POST['LoginForm'])) {
			$loginForm -> attributes = $_POST['LoginForm'];
			if($loginForm -> validate()) {
				$user -> setState('badLoginCount', null);
				$this -> redirect(Yii::app() -> user -> returnUrl);
			} else {
				$badLoginCount = $user -> getState('badLoginCount', 0);
				$user -> setState('badLoginCount', $badLoginCount + 1);
			}
		}
		$this->render("login", array(
			'login_form' => $loginForm,
			'scenario' => $scenario,
		));
	}

	public function actionLogout() {
		Yii::app()->user->logout();
		$this->redirect(array("site/index"));
	}

	public function actionSignUp() {
		if(!Yii::app()->user->isGuest) {
			Yii::app()->user->logout();
		}
		$scenario='userCreate';
		$user = new User($scenario);
		$this -> title = Yii::t("user", "Register new account"). " | " . Helper::getInstalledUrl();
		$flag = false;

		if(Yii::app() -> request -> isPostRequest && !empty($_POST['User'])) {
			$user -> attributes = $_POST['User'];
			if($user -> validate()) {
				$user->salt = Hasher::generateSalt();
				$user->password = Hasher::hashPassword($user->password, $user->salt);
				$transaction = Yii::app() -> db -> beginTransaction();
				try {
					$user -> role = User::ROLE_USER;
					$user -> email_confirmed = User::EMAIL_NOTCONFIRMED;
					$user -> can_send_message = User::ALLOW_MESSAGE;
					$user -> status = User::STATUS_ACTIVE;
                    $user -> lang_id = Yii::app()->language;
					if(!$user -> save(false)) {
						throw new CException("Unable to save user");
					}
					$this->onUserCreated(new CEvent($this, array(
						"user"=>$user,
					)));
					$transaction -> commit();
					$flag = true;
				} catch (Exception $e) {
					$transaction -> rollback();
					Yii::log($e->getMessage(), 'error', 'application.user.register');
					Yii::app() -> user -> setFlash('warning', Yii::t("notification", 'Server temporarily unavailable. Please, try to register a little bit later'));
					$this->refresh();
				}
			}
		}

		$tmpl = $flag ? "finish_reg" : "registration";

		$this->render($tmpl, array(
			"user" => $user
		));
	}

	public function actionConfirm() {
		$tok = Yii::app()->getRequest()->getQuery('token');
		$type = Yii::app()->getRequest()->getQuery('t');
        $this->title=Yii::t("user", "Email confirmation"). " | ".Helper::getInstalledUrl();
		if(!$token = UserToken::model()->get($tok, $type)) {
			throw new CHttpException(400, Yii::t("notification", "The token is expired or does not valid. Please, try to register new account"));
		}
		$transaction = Yii::app()->db->beginTransaction();
		$error = false;
		try {
			$user = new User;
			$token->status = UserToken::STATUS_ACTIVE;
			if(!$user->updateByPk($token->user_id, array("email_confirmed"=>User::EMAIL_CONFIRMED)) OR !$token->save()) {
				throw new CException("Unable to save records");
			}
			$transaction->commit();
		} catch (Exception $e) {
			$error = true;
			$transaction -> rollback();
			Yii::log($e->getMessage(), 'error', 'application.user.confirm');
		}
		$this->render("confirm", array(
			'error' => $error,
		));
	}

	public function actionForgotPassword() {
		$form = new ForgotPasswordForm();
		$this->title=Yii::t("user", "Forgot your password?"). " | ".  Helper::getInstalledUrl();

		if(Yii::app() -> request -> isPostRequest && !empty($_POST['ForgotPasswordForm'])) {
			$form -> attributes = $_POST['ForgotPasswordForm'];
			if($form -> validate()) {
				$userModel = User::model()->findByAttributes(array(
					'email' => $form->email,
				));

				$userToken = new UserToken;
				if(!$token = $userToken->createResetPassword($userModel)) {
					$form -> addError(null, Yii::t("notification", "Server temporarily unavailable. Try again later."));
				} else {
					$mailer = Yii::app()->mailer;
					$mailer->setFrom(Yii::app()->params["notificationEmail"], Yii::app()->params["notificationName"]);
					$mailer->Subject = Yii::t("user", "Password recovery").'. '. Helper::getBrandUrl();
					$mailer->AddAddress($userModel->email);
					$mailer->setPathViews("application.views.mail.user");
					$mailer->setPathLayouts("application.views.mail.layouts");
					$mailer->getView("reset_password", array(
						"name"=>Helper::mb_ucfirst($userModel->username),
                        "user"=>$userModel,
						"recoveryUrl"=>$this->createAbsoluteUrl("user/reset-password", array("t"=>$token->type, "token" => $token->token)),
					), "main");
					$mailer->AltBody=Yii::t("notification", 'Please, use mail client which support HTML markup');
					if($mailer->Send()) {
						Yii::app()->user->setFlash('success', Yii::t("notification", "We've sent you email with instructions. Please check your inbox"));
					} else {
						Yii::app()->user->setFlash('danger', Yii::t("notification", "An error occurred while sending email"));
					}
					$this->refresh();
				}
			}
		}

		$this->render("forgot_password", array(
			'form' => $form,
		));
	}

	public function actionResetPassword() {
		$tok = Yii::app()->getRequest()->getQuery('token');
		$type = Yii::app()->getRequest()->getQuery('t');
		if(!$token = UserToken::model()->get($tok, $type)) {
            throw new CHttpException(400, Yii::t("notification", "The token is expired or does not valid. Please, try to register new account"));
		}
		$this->title = Yii::t("user", 'Set new password');

		$scenario = 'tokenChange';
		$form = new ChangePasswordForm($scenario);

		if(Yii::app() -> request -> isPostRequest && !empty($_POST['ChangePasswordForm'])) {
			$form -> attributes = $_POST['ChangePasswordForm'];
			if($form -> validate()) {
				$transaction = Yii::app() -> db -> beginTransaction();
				try {
					$token->user->salt = Hasher::generateSalt();
					$token->user->password = Hasher::hashPassword($form->password, $token->user->salt);

					if(!$token->user->save(false)) {
						throw new CException("Unable to save new password. Restore password form");
					}

					$token->status = UserToken::STATUS_ACTIVE;
					if(!$token->save()) {
						throw new CException("Unable to update token. Restore password form");
					}

					$transaction -> commit();
					Yii::app() -> user -> setFlash('user', 'The password has been changed. Use new password to login');
					$this->redirect(array("user/sign-in"));
				} catch (Exception $e) {
					$transaction -> rollback();
					Yii::log($e->getMessage(), 'error', 'application.user.reset_password');
					Yii::app() -> user -> setFlash('error', Yii::t('notification', 'Server temporarily unavailable. Try again later.'));
					$this->refresh();
				}
			}
		}

		$this -> render('change_password', array(
			"form" => $form,
			"token" => $token,
		));
	}

	public function onUserCreated(CEvent $event) {
		$this->raiseEvent('onUserCreated', $event);
	}
}

protected/views/front/user/change_password.php
<form class="form-horizontal" method="POST">
	<fieldset>
		<legend>
			<?php echo CHtml::encode($this -> title) ?>
		</legend>
		<?php echo CHtml::errorSummary($form, null, null, array(
			'class' => 'alert alert-danger',
		)); ?>

		<?php if($form->scenario == "manualChange"): ?>
		<div class="form-group">
			<?php echo CHtml::activeLabel($form, 'oldpassword', array('class' => 'col-lg-2 control-label')); ?>
			<div class="col-lg-10">
				<?php echo CHtml::activePasswordField($form, 'oldpassword', array('class' => 'form-control')); ?>
			</div>
		</div>
		<?php endif; ?>

		<div class="form-group">
			<?php echo CHtml::activeLabel($form, 'password', array('class' => 'col-lg-2 control-label')); ?>
			<div class="col-lg-10">
				<?php echo CHtml::activePasswordField($form, 'password', array('class' => 'form-control')); ?>
			</div>
		</div>

		<div class="form-group">
			<?php echo CHtml::activeLabel($form, 'password2', array('class' => 'col-lg-2 control-label')); ?>
			<div class="col-lg-10">
				<?php echo CHtml::activePasswordField($form, 'password2', array('class' => 'form-control')); ?>
			</div>
		</div>

		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<?php echo CHtml::submitButton(Yii::t("user", "Reset password"), array(
					'class' => 'btn btn-large btn-primary',
				)); ?>
			</div>
		</div>
	<fieldset>
</form>

protected/views/front/user/confirm.php
<?php if(!$error): ?>
<h1>
    <?php echo Yii::t("user", "Congratulations!") ?>
</h1>
<p>
<?php echo Yii::t("user", "You have successfully confirmed your email address.") ?>
<br/><br/>
<a href="<?php echo $this->createUrl("user/sign-in") ?>" class="btn btn-primary""><?php echo Yii::t("user", "Sign in") ?></a>
</p>
<?php else: ?>
<div class="alert alert-warning">
    <strong><?php echo Yii::t("notification", "Attention!") ?></strong> <?php echo Yii::t("notification", "An error has occurred while trying to confirm your email. Please try again later.") ?>
</div>
<?php endif; ?>

protected/views/front/user/finish_reg.php
<h1><?php echo Yii::t("user", "Go check your email and confirm RIGHT NOW") ?></h1>
<p>
<?php echo Yii::t("user", "A confirmation email has been sent on {ConfirmationEmail}", array(
    "{ConfirmationEmail}"=>"<strong>".$user->email ."</strong>",
));
?>
</p>

protected/views/front/user/forgot_password.php
<form class="form-horizontal" method="POST">
	<fieldset>
		<legend>
			<?php echo Yii::t("user", "Forgot your password?") ?>
		</legend>
			<br/>
        <p>
					<?php echo Yii::t("user", "Forgot password instruction") ?>
        </p>

		<?php echo CHtml::errorSummary($form, null, null, array(
			'class' => 'alert alert-danger',
		)); ?>

		<div class="form-group">
			<?php echo CHtml::activeLabel($form, 'email', array('class' => 'col-lg-2 control-label')); ?>
			<div class="col-lg-10">
				<?php echo CHtml::activeTextField($form, 'email', array('class' => 'form-control')); ?>
			</div>
		</div>

		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<?php echo CHtml::submitButton(Yii::t("misc", "Submit"), array(
					'class' => 'btn btn-large btn-primary',
				)); ?>
				&nbsp; <a href="<?php echo $this->createUrl("user/sign-in") ?>"><?php echo Yii::t("user", "or wait, I remember!") ?></a>
			</div>
		</div>
	<fieldset>
</form>

protected/views/front/user/login.php
<div class="row">
	<div class="col-md-6 col-lg-6">
		<form class="form-horizontal" method="POST">
			<fieldset>
				<legend><p><?php echo Yii::t("user", "Login Form") ?></p></legend>

				<?php echo CHtml::errorSummary($login_form, null, null, array(
						'class' => 'alert alert-danger col-lg-offset-2',
				)); ?>

				<div class="form-group">
				<?php echo CHtml::activeLabel($login_form, 'email', array('class' => 'col-lg-2 control-label')); ?>
				<div class="col-lg-10">
				<?php echo CHtml::activeTextField($login_form, 'email', array('class' => 'form-control login')); ?>
				</div>
				</div>

				<div class="form-group">
				<?php echo CHtml::activeLabel($login_form, 'password', array('class' => 'col-lg-2 control-label')); ?>
				<div class="col-lg-10">
				<?php echo CHtml::activePasswordField($login_form, 'password', array('class' => 'form-control password')); ?>
				</div>
				</div>

				<?php if(CCaptcha::checkRequirements() AND $scenario): ?>
				<div class="form-group ">
				<?php echo CHtml::activeLabel($login_form, 'verifyCode', array('class'=> 'col-lg-2 control-label')); ?>

				<div class="col-lg-10">
				<?php $this->widget('CCaptcha', array(
					'buttonType' => 'button',
					'buttonOptions' => array(
						'class' => 'btn btn-sm btn-default',
					),
					'imageOptions' => array(
						'class' => '',
						'style' => 'float:left;',
					),
				)); ?>
				<div class="col-xs-4">
				<?php echo CHtml::activeTextField($login_form, 'verifyCode', array('class' => 'form-control col-lg-2')); ?>
				</div>
				</div>

				</div>
				<?php endif; ?>

				<div class="form-group">
					<div class="col-lg-offset-2 col-lg-10">
						<div class="checkbox">
								<label for="LoginForm_remember">
									<?php echo CHtml::activeCheckBox($login_form, 'remember'); ?><?php echo Yii::t("user", "Remember me"); ?>
								</label>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-lg-offset-2 col-lg-10">
						<button class="btn btn-sm btn-primary" type="submit"><?php echo Yii::t("user", "Sign in") ?></button>
					</div>
				</div>

			</fieldset>
		</form>
        <div class="col-lg-offset-2">
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="glyphicon glyphicon-lock"></span>
                    &nbsp;
                    <a href="<?php echo $this->createUrl("user/forgot-password") ?>">
                        <?php echo Yii::t("user", "Forgot your password?") ?>
                    </a>
                </li>
                <li class="list-group-item">
                    <span class="glyphicon glyphicon-pencil"></span>
                    &nbsp;
                    <?php echo Yii::t("user", "Don't have an account yet? {Sign up now}!", array(
											"{Sign up now}"=>CHtml::link(Yii::t("user", "Sign up now"), $this->createUrl("user/sign-up")),
                    )) ?>
                </li>
            </ul>
        </div>
	</div>
	<div class="col-md-5 col-md-offset-1 col-lg-5 col-lg-offset-1">
		<h3><?php echo Yii::t("user", "Need an account?") ?></h3>
        <br/>
        <p>
					<?php echo Yii::t("user", "Creating a {InstalledUrl} account is fast, easy, and free", array(
						"{InstalledUrl}"=>"<strong>".Helper::getBrandUrl()."</strong>",
					)) ?>
        </p>
        <br/>
        <a href="<?php echo $this->createUrl("user/sign-up") ?>" class="btn btn-primary btn-lg"><?php echo Yii::t("user", "Create an account") ?></a>
	</div>
</div>
<br/>

protected/views/front/user/registration.php
<div class="row">
    <div class="col-lg-12">
        <form class="form-horizontal" method="POST">
            <fieldset>
                <legend><p><?php echo Yii::t("user", "Register Form") ?></p></legend>
                <br/>
                <p class="col-lg-offset-2">
									<?php echo Yii::t("user", "{Click here} if you already have an account and just need to login.", array(
										"{Click here}"=>CHtml::link(Yii::t("misc", "Click here"), $this->createUrl("user/sign-in")),
									)) ?>
                </p>
                <br/>

                <?php echo CHtml::errorSummary($user, null, null, array(
                    'class' => 'alert alert-danger col-lg-offset-2',
                )); ?>

                <div class="form-group">
                    <?php echo CHtml::activeLabel($user, 'email', array('class' => 'col-lg-2 control-label')); ?>
                    <div class="col-lg-10">
                        <?php echo CHtml::activeTextField($user, 'email', array(
                            'class' => 'form-control login',
                            'required'=>true,
                            'type'=>'email',
                            'placeholder'=>Yii::t("user", "Email"),
                            'autofocus'=>true,
                        )); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo CHtml::activeLabel($user, 'password', array('class' => 'col-lg-2 control-label')); ?>
                    <div class="col-lg-10">
                        <?php echo CHtml::activePasswordField($user, 'password', array(
                            'class' => 'form-control password',
                            'required'=>true,
                            'placeholder'=>Yii::t("user", "Password"),
                        )); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo CHtml::activeLabel($user, 'password2', array('class' => 'col-lg-2 control-label')); ?>
                    <div class="col-lg-10">
                        <?php echo CHtml::activePasswordField($user, 'password2', array(
                            'class' => 'form-control password',
                            'required'=>true,
                            'placeholder'=>Yii::t("user", "Re-Password"),
                        )); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo CHtml::activeLabel($user, 'username', array('class' => 'col-lg-2 control-label')); ?>
                    <div class="col-lg-10">
                        <?php echo CHtml::activeTextField($user, 'username', array(
                            'class' => 'form-control login',
                            'required'=>true,
                            'placeholder'=>Yii::t("user", "Username"),
                        )); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-lg btn-primary" type="submit"><?php echo Yii::t("user", "Sign up") ?></button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>