protected/models/Website.php
<?php
class Website extends CActiveRecord {
	/**
	* @param string $className
	* @return Website
	*/
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{webdata_main}}';
	}

	public function relations() {
		return array(
			'alexa'=>array(self::HAS_ONE, 'WebdataAlexa', 'wid'),
			'antivirus'=>array(self::HAS_ONE, 'WebdataAntivirus', 'wid'),
			'catalog'=>array(self::HAS_ONE, 'WebdataCatalog', 'wid'),
			'location'=>array(self::HAS_ONE, 'WebdataLocation', 'wid'),
			'meta_tags'=>array(self::HAS_ONE, 'WebdataMetaTags', 'wid'),
			'search_engine'=>array(self::HAS_ONE, 'WebdataSearchEngine', 'wid'),
			'social'=>array(self::HAS_ONE, 'WebdataSocial', 'wid'),
			'whois'=>array(self::HAS_ONE, 'WebdataWhois', 'wid'),
			'sale'=>array(self::HAS_ONE, 'Sale', 'website_id'),
			'sale_stat'=>array(self::STAT, 'Sale', 'website_id'),
		);
	}

	public function beforeSave() {
		if(parent::beforeSave()) {
			$now = date("Y-m-d H:i:s");
			if($this->isNewRecord) {
				$this -> added_at = $now;
				$this -> modified_at = $now;
				$this->md5domain = md5($this->domain);
			} else {
				$this -> modified_at = $now;
			}
			return true;
		} else {
			return false;
		}
	}

	public $sale_search='-1';
	public function search() {
		Yii::import("application.library.IDN");
		$idn=new IDN;
		$criteria=new CDbCriteria;
		$criteria->order = 't.added_at DESC';

		$criteria->compare('t.id', $this->id);
		$domain=$idn->encode(Helper::trimDomain($this->domain));
		if(!empty($domain)) {
			$criteria->compare('t.md5domain', md5($domain));
		}
		$criteria->compare('t.price', $this->price, true);

		if((string)$this->sale_search==='1') {
			$criteria->compare('sale.website_id', '>0');
		} elseif((string)$this->sale_search==='0') {
			$criteria->condition ='sale.website_id IS NULL';
		}

		$criteria->with = array(
			"sale"=>array(
				"select"=>"sale.website_id",
			),
		);
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public function rules() {
		return array(
			array('price, domain, idn', 'required'),

			// Search
			array('id, domain, price, sale_search', 'safe', 'on' => 'search'),
		);
	}

	public function attributeLabels() {
		return array(
			"id"=>Yii::t("misc", "ID"),
			"domain"=>Yii::t("website", "Domain"),
			"idn"=>Yii::t("website", "Domain"),
			"added_at"=>Yii::t("misc", "Added at"),
			"modified_at"=>Yii::t("user", "Modified at"),
			"price"=>Yii::t("website", "Estimate Price"),
			"sale_search"=>Yii::t("website", "Is On Sale"),
		);
	}
}

protected/controllers/WebsiteController.php
<?php
Yii::import("ext.ecountrylist.*");

class WebsiteController extends FrontController {
	public function actionCalculate() {
		if(isset($_GET['CalculationForm']) AND is_array($_GET['CalculationForm'])) {
			// Very strange bug. If imagick extension is loaded - the php native function unable to resolve IP
			// We call gethostbyname before checking the CAPTCHA, so the result will be cached.
			if(isset($_GET['CalculationForm']['domain']) AND extension_loaded('imagick')) {
				gethostbyname($_GET['CalculationForm']['domain']);
			}
			
			$scenario = Helper::isAllowedCaptcha() ? "protectedRequest" : null;
			$form=new CalculationForm($scenario);
			//$form->scenario=Yii::app()->request->getQuery('scenario');
			$form->attributes=$_GET['CalculationForm'];
			//$form->domain="php5developer.com";
			//var_dump(Yii::app()->controller->createAction('captcha')->getVerifyCode());
			if(!$form->validate()) {
				$this->jsonResponse($form -> getErrors());
			}
			$website=$form->getWebsite();
			if(Helper::isAllowedCaptcha()) {
				Yii::app()->controller->createAction('captcha')->getVerifyCode(true);
			}
			$redirect = strtr(Yii::app()->request->getQuery('redirect'), array(
				'__ID__'=> $website->id,
				'__DOMAIN__'=>$website->domain,
			));
			$instant=(bool) Yii::app()->request->getQuery('instant');
			if($instant) {
				$this->redirect($redirect);
			} else {
				$this->jsonResponse($redirect);
			}
		}
	}

	public function actionShow($domain) {
		if(!$website = Website::model()->with(array(
			"alexa", "antivirus", "catalog", "location", "meta_tags", "search_engine", "social", "whois",
			"sale"=>array(
				"with"=>array(
					"category"=>array(
						"with"=>array(
							"translations"=>array(
								"scopes"=>array("current_lang"),
							),
						),
					),
					"user"=>array(
						"select"=>"id",
					),
				),
			),
		))->findByAttributes(array(
			"md5domain"=>md5($domain),
		))) {
			if(Yii::app()->params["autoCalculation"] AND !Yii::app()->params["captcha"]) {
				$form=new CalculationForm;
				$form->domain=$domain;
				if($form->validate()) {
					$this->redirect($this->createUrl("website/show", array("domain"=>$domain)));
				}
			}
			throw new CHttpException(404, Yii::t("notification", "The page you are looking for doesn't exists"));
		}
		Yii::import("application.library.Estimator");
		$estimator = new Estimator($website->alexa->rank);
		
		$thumbnail=WebsiteThumbnail::getUrl(array(
			'{{Url}}'=>$website->domain,
			'{{Size}}'=>'l',
		));

		$this->title = Yii::t("website", "{Website} worth is {Cost}", array(
			"{Website}"=>$website->idn,
			"{Cost}"=>html_entity_decode(Helper::p($website->price)),
		));
		$cs=Yii::app()->clientScript;
		$cs->registerMetaTag(Yii::t("website", "website keywords", array("{Website}"=>$website->idn)), 'keywords');
		$cs->registerMetaTag($this->title, 'description');

		$url=$this->createAbsoluteUrl("website/show", array("domain"=>$website->domain));
		$cs->registerMetaTag(Yii::t("website", "Website cost"),null,null,array('property'=>'og:title'));
		$cs->registerMetaTag($this->title,null,null,array('property'=>'og:description'));
		$cs->registerMetaTag($url,null,null,array('property'=>'og:url'));
		$cs->registerMetaTag($thumbnail,null,null,array('property'=>'og:image'));


		$update = (time() - strtotime($website->modified_at)) > Yii::app() -> params["webdataCache"];
		$time = Yii::app()->dateFormatter->formatDateTime($website->modified_at, 'long', 'medium');
		if(!Yii::app()->user->isGuest AND $website->sale) {
			$box=Yii::app()->innerMail->box(Yii::app()->user->loadModel());
			$block=$box->getBlock($website->sale->user->id);
		} else {
			$block=null;
		}

		$updateLink=$this->createUrl("website/calculate", array(
				"instant"=>1,
				"redirect"=>$this->createUrl("website/show", array("domain"=>$website->domain)),
				"CalculationForm"=>array(
						"domain"=>$website->domain,
				)
		));

		$widget=$this->renderPartial("/{$this->_end}/website/widget", array(
			"url"=>$this->createAbsoluteUrl("website/show", array("domain"=>$website->domain)),
			"domain"=>$website->idn,
			"price"=>Helper::p($website->price),
		), true);

		$this->render("show", array(
			"website"=>$website,
			"update"=>$update,
			"time"=>$time,
			"widget"=>$widget,
			"block"=>$block,
			"thumbnail"=>$thumbnail,
			"updateLink"=>$updateLink,
			"country"=>ECountryList::getInstance(Yii::app()->language),
			"estimator"=>$estimator,
			"dailyVisitors"=>$estimator->getEstimatedUniqueDailyVisitors(),
			"dailyPageviews"=>$estimator->getEstimatedDailyPageViews(),
			"dailyAdsRevenue"=>$estimator->getEstimatedDailyAdsRevenue(),
			"monthlyVisitors"=>$estimator->getEstimatedUniqueMonthlyVisitors(),
			"monthlyPageviews"=>$estimator->getEstimatedMonthlyPageViews(),
			"monthlyAdsRevenue"=>$estimator->getEstimatedMonthlyAdsRevenue(),
			"yearlyVisitors"=>$estimator->getEstimatedUniqueYearlyVisitors(),
			"yearlyPageviews"=>$estimator->getEstimatedYearlyPageViews(),
			"yearlyAdsRevenue"=>$estimator->getEstimatedYearlyAdsRevenue(),
		));
	}

	public function actionTopList() {
		$page = (int) Yii::app()->request->getQuery('page', 1);
		$this->title = Yii::t("website", "Top websites by price. Page {PageNr}", array(
			"{PageNr}"=>$page,
		));
		$cs=Yii::app()->clientScript;
		$cs->registerMetaTag($this->title, 'keywords');
		$cs->registerMetaTag($this->title, 'description');

        $total=Website::model()->cache(3600)->count();
		$widget = $this->widget('application.widgets.WebsiteList', array(
			"config"=>array(
				"criteria"=>array(
					"order"=>"t.price DESC"
				),
                "totalItemCount"=>$total,
			),
		), true);
		$this->render("website_list", array(
			"widget"=>$widget,
			'afterHeader'=>$this->renderPartial("top_breadcrumbs", array(), true),
		));
	}

	public function actionCountryList($id = null, $page = null) {
		$page = $page == null ? 1 : $page;
		$this->title = Yii::t("website", 'Top websites by countries. Diagram. Page {PageNr}', array(
			"{PageNr}"=>$page,
		));
		$cs=Yii::app()->clientScript;
		$cs->registerMetaTag($this->title, 'keywords');
		$cs->registerMetaTag($this->title, 'description');

		$raw = WebdataLocation::model()->cache(60*60*5)->countryGroup()->findAll();
		$dataProvider = new CArrayDataProvider($raw, array(
			'pagination' => array(
				'pageSize' => Yii::app()->params['countriesPerPage'],
			),
		));
		$topCountries=array();
		$sum = 0;
		$top = 10;
		$topCountries = array_slice($raw, 0, $top);
		foreach($topCountries as $row) {
			$sum += $row->countryTotal;
		}

		Yii::app()->clientScript->registerScriptFile(Yii::app()->request->getBaseUrl(true).'/js/jquery.flot.js');
		Yii::app()->clientScript->registerScriptFile(Yii::app()->request->getBaseUrl(true).'/js/jquery.flot.pie.js');

		$this->render("country_list", array(
			"sum" => $sum,
			"topCountries" => $topCountries,
			"top" => $top,
			"dataProvider" => $dataProvider,
			"country" => ECountryList::getInstance(Yii::app()->language),
		));
	}

	public function actionCountry($id, $page = null) { // Country
		$page = $page == null ? 1 : $page;
		$country = ECountryList::getInstance(Yii::app()->language);
		$countryName = $country->getCountryName($id);
		$this->title = Yii::t("website", "Top websites in {Country}. Page {PageNr}", array(
			"{Country}"=>$countryName,
			"{PageNr}"=>$page,
		));
		$cs=Yii::app()->clientScript;
		$cs->registerMetaTag($this->title, 'keywords');
		$cs->registerMetaTag($this->title, 'description');

		$criteria = new CDbCriteria;
		$criteria->condition="country_code=:country_code";
		$criteria->params=array(":country_code"=>$id);
		$total=WebdataLocation::model()->cache(60*60)->count($criteria);

		$widget = $this->widget('application.widgets.WebsiteList', array(
			"config"=>array(
				"totalItemCount"=>$total,
				"criteria"=>array(
					"with"=>array(
						"location" => array(
							"select"=>"country_code",
						),
					),
					"condition"=>"location.country_code=:country_code",
					"params"=>array(":country_code"=>$id),
					"order"=>"t.price DESC"
				),
			),
		), true);

		$this->render("website_list", array(
			"afterHeader"=>$this->renderPartial("top_breadcrumbs", array(), true),
			"widget"=>$widget,
		));
	}

	public function actionPageRankList() {
		$this->title = Yii::t("website", 'Top websites by PageRank. Diagram');
		$cs=Yii::app()->clientScript;
		$cs->registerMetaTag($this->title, 'keywords');
		$cs->registerMetaTag($this->title, 'description');

		Yii::app()->clientScript->registerScriptFile(Yii::app()->request->getBaseUrl(true).'/js/jquery.flot.js');
		Yii::app()->clientScript->registerScriptFile(Yii::app()->request->getBaseUrl(true).'/js/jquery.flot.pie.js');

		$raw = WebdataSearchEngine::model()->cache(60*60)->prGroup()->findAll();
		$pageRankIndex=array();
		$sum = 0;
		foreach($raw as $row) {
			$pageRankIndex[$row->page_rank] = $row->prTotal;
			$sum += $row->prTotal;
		}

		$prRange = array_merge(array('n-a'), range(0, 10));
		$this->render("page_rank_list", array(
			"pageRankIndex" => $pageRankIndex,
			"sum" => $sum,
			"prRange" => $prRange,
		));
	}

	public function actionPageRank($id, $page = null) { // Page rank number
		$page = $page == null ? 1 : $page;
		$this->title = Yii::t("website", "Top websites having {PageRank} PageRank. Page {PageNr}", array(
			"{PageRank}"=>$id,
			"{PageNr}"=>$page,
		));

		$criteria = new CDbCriteria;
		$criteria->condition="page_rank=:page_rank";
		$criteria->params=array(":page_rank"=>$id);
		$total=WebdataSearchEngine::model()->cache(60*60)->count($criteria);

		$widget = $this->widget('application.widgets.WebsiteList', array(
			"config"=>array(
				"totalItemCount"=>$total,
				"criteria"=>array(
					"condition"=>"page_rank=:page_rank",
					"params"=>array(":page_rank"=>$id),
					"order"=>"t.price DESC"
				),
			),
		), true);

		$this->render("website_list", array(
			"afterHeader"=>$this->renderPartial("top_breadcrumbs", array(), true),
			"widget"=>$widget,
		));
	}

protected/views/front/website/country_list.php
<script type="text/javascript">
$(document).ready(function(){
	var pie_data = [];

	<?php $i=0; foreach($topCountries as $topCountry) : ?>
	pie_data[<?php echo $i ?>] = {
		label: '&nbsp;&nbsp;<?php echo $country->getCountryName($topCountry->country_code, strtoupper($topCountry->country_code)) . ' ('. Helper::proportion($sum, $topCountry->countryTotal). '%)' ?>',
		data: <?php echo $topCountry->countryTotal ?>,
	}
	<?php $i++; endforeach; ?>

	drawFlot();
	window.onresize = function(event) {
		drawFlot();
	}
	function drawFlot() {
		$.plot($("#country-pie"), pie_data, {
			series: {
				pie: {
					show: true
				}
			}
		});
	}

});
</script>

<h1 align="center"><?php echo CHtml::encode($this->title) ?></h1>

<div class="row">
	<div id="country-pie" style="max-width:450px; height:200px; margin:0 auto;"></div>
</div>
<br/>
<?php $this->renderPartial("top_breadcrumbs") ?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th><?php echo Yii::t("website", "Country") ?></th>
			<th><?php echo Yii::t("website", "Number of websites") ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($dataProvider->getData() as $data): $url = $this->createUrl("website/country", array("id"=>strtolower($data->country_code))) ?>
		<tr>
			<td class="cell-link" width="80%">
				<a href="<?php echo $url ?>">
					<?php echo $country->getCountryName($data->country_code, strtoupper($data->country_code)) ?>
				</a>
			</td>
			<td class="cell-link">
				<a href="<?php echo $url ?>">
					<?php echo $data->countryTotal ?>
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div class="pull-right">
<?php $this -> widget('CLinkPager', array(
	'pages' => $dataProvider->getPagination(),
	'htmlOptions' => array(
		'class' => 'pagination',
	),
	'cssFile' => false,
	'header' => '',
	'hiddenPageCssClass' => 'disabled',
	'selectedPageCssClass' => 'active',
)); ?>
</div>
<div class="clearfix"></div>

protected/views/front/website/page_rank_list.php
<script type="text/javascript">
$(document).ready(function(){
	var pie_data = [];

	<?php $i=0; foreach($pageRankIndex as $pr => $total) : ?>
	pie_data[<?php echo $i ?>] = {
		label: '&nbsp;&nbsp;<?php echo Yii::t("website", "Page Rank") ." ". $pr . ' ('. Helper::proportion($sum, $total). '%)' ?>',
		data: <?php echo $total ?>,
	}
	<?php $i++; endforeach; ?>

	drawFlot();
	window.onresize = function(event) {
		drawFlot();
	}
	function drawFlot() {
		$.plot($("#pr-pie"), pie_data, {
			series: {
				pie: {
					show: true
				}
			}
		});
	}

});
</script>

<h1 align="center"><?php echo CHtml::encode($this->title) ?></h1>

<div class="row">
	<div id="pr-pie" style="max-width:400px;height:200px; margin:0 auto;"></div>
</div>
<br/>
<?php $this->renderPartial("top_breadcrumbs") ?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th><?php echo Yii::t("website", "Page Rank") ?></th>
			<th><?php echo Yii::t("website", "Number of websites") ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($prRange as $pr): $url = $this->createUrl("website/page-rank", array("id"=>$pr)) ?>
		<tr>
			<td class="cell-link" width="80%">
				<a href="<?php echo $url ?>">
					<?php echo $pr ?>
				</a>
			</td>
			<td class="cell-link">
				<a href="<?php echo $url ?>">
					<?php echo isset($pageRankIndex[$pr]) ? $pageRankIndex[$pr] : 0 ?>
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

protected/views/front/website/sell.php
<h1><?php echo Yii::t("sale_instruction", "Sell Websites - Sell Domains") ?></h1>

<p><?php echo Yii::t("sale_instruction", "Do you want to sell your website, sell your domain name?") ?></p>

<p>
<?php echo Yii::t("sale_instruction", "{Portal} allows people you to sell your website.", array(
	"{Portal}"=>"<strong>".$brandUrl."</strong>",
)) ?>
</p>

<p><?php echo Yii::t("sale_instruction", "To tell people that you may sell your website or sell domain") ?></p>

<ol>
<li>
	<?php echo Yii::t("sale_instruction", "Register/Login to {Portal}", array(
		"{Portal}"=> "<strong>".$brandUrl."</strong>",
	)) ?>
</li>
<li>
	<?php echo Yii::t("sale_instruction", "Check your website/domain on {Portal}", array(
		"{Portal}"=>"<strong>".$brandUrl."</strong>",
	)) ?>
</li>
<li>
	<?php echo Yii::t("sale_instruction", 'After analysis and calculation of your website price done, click "Sell my website/domain"', array(
		"{Portal}"=>"<strong>".$brandUrl."</strong>",
	)); ?>
</li>
<li>
	<?php echo Yii::t("sale_instruction", "Site Verification page opens", array(
		"{Portal}"=>"<strong>".$brandUrl."</strong>",
	)) ?>
</li>
<li>
	<?php echo Yii::t("sale_instruction", "Check your domain/website listed on {Buy Websites} page", array(
		"{Buy Websites}"=>CHtml::link(Yii::t("misc", "Buy Websites"), $this->createUrl("category/index")),
	)) ?>
</li>
<li>
	<?php echo Yii::t("sale_instruction", "And wait for people contact with you.") ?>
</li>
</ol>
<br/>
<a class="btn btn-primary" href="<?php echo $this->createUrl("category/index") ?>"><?php echo Yii::t("sale_instruction", "Check websites and domains on sale") ?></a>
<br/><br/>

protected/views/front/website/top_breadcrumbs.php
<ul class="nav nav-pills nav-justified">
	<li<?php echo stripos($this->action->id, 'top') !== false ? ' class="active"' : null; ?>>
		<a href="<?php echo $this->createUrl("website/toplist") ?>">
			<?php echo Yii::t("website", "TOP by Cost") ?>
		</a>
	</li>
	<li<?php echo stripos($this->action->id, 'pagerank') !== false ? ' class="active"' : null; ?>>
		<a href="<?php echo $this->createUrl("website/page-ranklist") ?>">
			<?php echo Yii::t("website", "TOP by PageRank") ?>
		</a>
	</li>
	<li<?php echo stripos($this->action->id, 'country') !== false ? ' class="active"' : null; ?>>
		<a href="<?php echo $this->createUrl("website/countrylist") ?>">
			<?php echo Yii::t("website", "TOP by Countries") ?>
		</a>
	</li>
</ul>
<br/>

protected/views/front/website/website_list.php
<h1><?php echo CHtml::encode($this->title) ?></h1>

<?php if(isset($afterHeader)): ?>
<?php echo $afterHeader; ?>
<?php endif; ?>

<div class="clearfix"></div>

<?php echo $widget ?>

protected/views/front/website/widget.php
<div style="max-width:200px; font-size: 12px; word-wrap: break-word; text-align:center; background-color: #ffffff; border: 1px solid #dddddd; -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.05); box-shadow: 0 1px 1px rgba(0,0,0,0.05);">
  <div style="color: #333333; background-color: #f5f5f5; padding:5px; border-bottom: 1px solid #dddddd;">
    <a style="color: #008cba; text-decoration: underline;" href="<?php echo $url ?>" target="_blank">
      <?php echo $domain ?>
    </a>
  </div>
  <div style="padding:5px; color: #222222; line-height: 1.5;">
    <?php echo Yii::t("website", "Estimated worth") ?><br/>
    &#8226;&nbsp;<span style="font-size: 14px"><strong><?php echo $price ?></strong></span>&nbsp;&#8226;
  </div>
</div>